//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fopex.DAL.dbxEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Category
    {
        public Account_Category()
        {
            this.Account_Subcategory = new HashSet<Account_Subcategory>();
        }
    
        public int ID { get; set; }
        public string Account_Category_Description { get; set; }
    
        public virtual ICollection<Account_Subcategory> Account_Subcategory { get; set; }
    }
}
