//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fopex.DAL.dbxEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Subcategory
    {
        public int ID { get; set; }
        public Nullable<int> Account_Subcategory_Code { get; set; }
        public string Account_Subcategory_Description { get; set; }
        public Nullable<int> Account_CategoryID { get; set; }
    
        public virtual Account_Category Account_Category { get; set; }
    }
}
