//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fopex.DAL.dbxEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_Units
    {
        public int ID { get; set; }
        public string Business_Unit_Code { get; set; }
        public string Business_Unit_Description { get; set; }
    }
}
