//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fopex.DAL.dbxEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_Main_Category
    {
        public int ID { get; set; }
        public Nullable<int> Main_GL_Code { get; set; }
        public string Main_GL_Description { get; set; }
    }
}
