//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fopex.DAL.dbxEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Ledger
    {
        public int Transaction_No { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Transaction_Type { get; set; }
        public string Item_No { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
