//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fopex.DAL.dbxEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID { get; set; }
        public string Item_No { get; set; }
        public string item_Description { get; set; }
        public string UOM_ID { get; set; }
        public string Item_Type_ID { get; set; }
        public string Purch_UOM_ID { get; set; }
        public string Sale_UOM_ID { get; set; }
        public Nullable<int> Prod_UOM_ID { get; set; }
        public Nullable<int> Qty_Purch_Ord_ID { get; set; }
        public Nullable<int> Qty_Sale_Ord_ID { get; set; }
        public Nullable<int> Qty_Prod_Ord_ID { get; set; }
        public Nullable<int> Qty_BOM_ID { get; set; }
        public Nullable<int> Qty_Available { get; set; }
        public Nullable<int> Qty_Sold { get; set; }
        public Nullable<int> Qty_Adj { get; set; }
        public string Business_Unit_ID { get; set; }
        public string Product_Line_ID { get; set; }
        public string Product_Group_ID { get; set; }
        public string Item_Category_ID { get; set; }
        public string GLCodeID_Sale { get; set; }
        public string GLCodeID_Inventory { get; set; }
        public string GLCodeID_CostofSale { get; set; }
    
        public virtual Item Item1 { get; set; }
        public virtual Item Item2 { get; set; }
    }
}
