//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fopex.DAL.dbxEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerTransaction
    {
        public int ID { get; set; }
        public string Transaction_ID { get; set; }
        public string Transaction_Type { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<int> Date { get; set; }
        public string CostCenter { get; set; }
        public string Code_Level1 { get; set; }
        public string Code_Level2 { get; set; }
        public string Code_Level3 { get; set; }
        public Nullable<int> AmountDebit { get; set; }
        public Nullable<int> AmountCredit { get; set; }
    }
}
