//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fopex.DAL.dbxEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PettyCashForm
    {
        public int PettyCashID { get; set; }
        public string CashierName { get; set; }
        public string LocationID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string CashType { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string TransactionType { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public Nullable<double> ReceiptAmount { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> PhysicalCashinHand { get; set; }
        public Nullable<double> CashDifference { get; set; }
        public string GLAccountID { get; set; }
        public Nullable<double> IOU { get; set; }
    }
}
