//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fopex.DAL.dbxEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationMaster
    {
        public long Id { get; set; }
        public long RegionId { get; set; }
        public long CurrencyId { get; set; }
        public string QutationNo { get; set; }
        public string QRRNo { get; set; }
        public long CustumerId { get; set; }
        public string QutationSubject { get; set; }
        public System.DateTime QutationDate { get; set; }
        public System.DateTime QutationValidity { get; set; }
        public int CustomrRepresentativeId { get; set; }
        public long QutationSentByUserId { get; set; }
        public Nullable<decimal> GrossTotal { get; set; }
        public Nullable<decimal> ApplicableDiscount { get; set; }
        public Nullable<decimal> ImportDuties { get; set; }
        public Nullable<decimal> CustomDuties { get; set; }
        public long QutationStatus { get; set; }
        public string BarCodeId { get; set; }
        public string BarCodeImageUlr { get; set; }
        public string PaymnetTernsAndCondition { get; set; }
        public string SpecialNotes { get; set; }
        public int VersionNo { get; set; }
        public string Data { get; set; }
        public long TermAndConditionId { get; set; }
        public Nullable<long> VendorQutationId { get; set; }
        public Nullable<long> TaxId { get; set; }
        public Nullable<long> AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<long> VersionOf { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
        public string UploadedFileUrl { get; set; }
    }
}
