//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fopex.DAL.dbxEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationDetail
    {
        public long Id { get; set; }
        public string PartNo { get; set; }
        public string Serial_No { get; set; }
        public Nullable<long> BrandId { get; set; }
        public string BrandName { get; set; }
        public string Description { get; set; }
        public long UOMId { get; set; }
        public string UOMName { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> GrossPrice { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<long> MarginType { get; set; }
        public Nullable<decimal> UnitPriceAfterMargin { get; set; }
        public Nullable<decimal> GrossPriceAfterMargin { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public long DiscountTypeId { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public long CurrencyId { get; set; }
        public long QutationId { get; set; }
        public long VendorQuotationId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public decimal DiscountedValueAmount { get; set; }
        public decimal MarginValueAmount { get; set; }
    }
}
